version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mantasedine33
      POSTGRES_DB: Nest-test
    networks:
      - Mantas
networks:
  Mantas:
